apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume
  namespace: knative-serving
spec:
  containers:
  - name: test-projected-volume
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: all-in-one
      mountPath: "/etc/certs"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: paarijaat-debian-vm
      - secret:
          name: paarijaat-debian-vm-2